name: serverless-api
kind: Project
backend: aws-backend
variables:
  organization: my-organization
  region: us-east-1
  state_bucket_name: cluster-dev-state
# exports:
#   AWS_PROFILE: <aws_profile>
#  CDEV_TF_BINARY: /usr/local/bin/terraform-0.14.9 # optional set of TF version

