name: serverless-api
kind: Project
backend: aws-backend
variables:
  organization: my-organization
  region: us-east-1
  state_bucket_name: cluster-dev-state
  account_id: 123456789
  api_name: my-cdev-serverless-api
  lambda_function_name: my-cdev-function
