name: serverless-api
template: ./template/
kind: Stack
backend: aws-backend
variables:
  api_name: {{ .project.variables.api_name }}
  lambda_function_name: {{ .project.variables.lambda_function_name }}
  region: {{ .project.variables.region }}
  account_id: {{ .project.variables.account_id }}
