description: Serverless API on AWS Cloud
options:
  - name: name
    description: Project name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: "serverless-api-project"
  - name: organization
    description: Organization name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: "my-organization"
  - name: region
    description: AWS region
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,32}$"
    default: "us-east-1"
  - name: api_name
    description: Serverless API name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: "my-cdev-serverless-api"
  - name: function_name
    description: Lambda function name
    regex: "^[a-zA-Z][a-zA-Z_0-9\\-]{0,64}$"
    default: "my-cdev-function"
  - name: bucket_name
    description: AWS S3 bucket name for states
    regex: "^[a-zA-Z][a-zA-Z0-9\\-]{0,64}$"
    default: "cdev-state"
  - name: account_id
    description: AWS account id
    regex: "^[0-9]{12}$"
    default: "123456789"
help_message: | 
  ###############################################################################
  # Cluster.dev project generation for AWS cloud.                                #
  # cdev console tool generator                                                 #
  ###############################################################################
  Before your begin:                                           
  1) Export environment variables (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY or use profile AWS_PROFILE) for AWS auth. Details: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
  2) Create S3 bucket for Terraform states: 
        aws s3 mb s3://mybucket-name
  3) Use cdev command to plan and apply project infrastructure